-- TCM-5 anomaly-detection sink schema.
-- Conventions:
--   * lowercase snake_case column names  (Flink JDBC sink maps by column name)
--   * TIMESTAMP (not TIMESTAMPTZ); the Flink session runs in UTC so Grafana
--     "last N minutes" filters line up with the stored wall-clock.

-- ---------------------------------------------------------------------------
-- Per-event grain: one row per scored per-stand reading (append-only).
-- reading_id is generated by Postgres; the Flink sink never inserts it, so
-- dashboards dedup at-least-once replay with DISTINCT ON (coil_id, stand)
-- ORDER BY reading_id DESC (latest write wins).
--
-- The fact table is RANGE-partitioned on ts (native PG declarative partitioning —
-- no extension, stock image). Rows route to the right daily partition on insert,
-- transparently to the Flink sink and every reader. Two payoffs: time-bounded
-- panel queries ($__timeFilter(ts)) prune to the relevant partitions, and data
-- retention is an instant DROP/DETACH of an old partition instead of a slow bulk
-- DELETE (see scripts/partitions.sh). The partition key must be part of the PK,
-- so the PK is (reading_id, ts); the identity sequence still keeps reading_id
-- globally unique, and nothing does point lookups on reading_id alone.
-- ---------------------------------------------------------------------------
CREATE TABLE scored_events (
  reading_id        BIGINT GENERATED ALWAYS AS IDENTITY,
  ts                TIMESTAMP(3) NOT NULL,
  coil_id           BIGINT,
  stand             INT,
  file_no           INT,
  -- ALL 16 model features are logged here so the retrain sidecar can train on the
  -- streamed data directly (the PROCESS/KPI panels chart the measured subset).
  work_roll_diam    DOUBLE PRECISION,
  work_roll_mileage DOUBLE PRECISION,
  reduction         DOUBLE PRECISION,
  roll_speed        DOUBLE PRECISION,
  force             DOUBLE PRECISION,
  torque            DOUBLE PRECISION,
  gap               DOUBLE PRECISION,
  motor_power       DOUBLE PRECISION,
  thickness_entry   DOUBLE PRECISION,
  thickness_exit    DOUBLE PRECISION,
  width             DOUBLE PRECISION,
  ys_entry          DOUBLE PRECISION,
  ys_exit           DOUBLE PRECISION,
  tension_in        DOUBLE PRECISION,
  tension_out       DOUBLE PRECISION,
  -- model outputs
  anomaly_score     DOUBLE PRECISION,
  p_electric        DOUBLE PRECISION,
  p_bearing         DOUBLE PRECISION,
  p_workroll        DOUBLE PRECISION,
  p_reduction       DOUBLE PRECISION,
  -- ground-truth labels (carried by the producer; the model never overwrites them)
  y_electric        BOOLEAN,
  y_bearing         BOOLEAN,
  y_workroll        BOOLEAN,
  y_reduction       BOOLEAN,
  y_any             BOOLEAN,
  model_version     INT,
  -- model-free unsupervised detectors + their 2-of-3 majority vote (computed in Flink,
  -- always available, even before any model is trained: Mahalanobis / SPC / kNN)
  u_maha            DOUBLE PRECISION,
  u_spc             DOUBLE PRECISION,
  u_knn             DOUBLE PRECISION,
  u_votes           INT,
  u_anomaly         BOOLEAN,
  -- Stamped by Postgres on insert (the Flink sink never lists this column, same
  -- mechanism as reading_id). ingested_at - ts = true end-to-end pipeline latency
  -- (producer emit -> Kafka -> Flink UDF -> JDBC sink -> Postgres), both in UTC.
  ingested_at       TIMESTAMP(3) DEFAULT (now() AT TIME ZONE 'utc'),
  PRIMARY KEY (reading_id, ts)
) PARTITION BY RANGE (ts);

-- Daily partitions for a rolling window around bootstrap time, plus a DEFAULT
-- partition so an out-of-window ts can never make an insert fail. scripts/partitions.sh
-- extends the window forward and drops partitions past the retention horizon.
DO $$
DECLARE d date;
BEGIN
  FOR d IN SELECT generate_series(CURRENT_DATE - 1, CURRENT_DATE + 14, interval '1 day')::date
  LOOP
    EXECUTE format(
      'CREATE TABLE IF NOT EXISTS scored_events_%s PARTITION OF scored_events '
      'FOR VALUES FROM (%L) TO (%L)', to_char(d, 'YYYYMMDD'), d, d + 1);
  END LOOP;
END $$;
CREATE TABLE IF NOT EXISTS scored_events_default PARTITION OF scored_events DEFAULT;

-- Indexes declared on the parent propagate to every existing and future partition.
CREATE INDEX idx_scored_events_ts         ON scored_events (ts);
-- Supports the DISTINCT ON (coil_id, stand) ... ORDER BY reading_id DESC dedup the
-- dashboard and the retrain sidecar rely on (ordered index scan instead of a sort).
CREATE INDEX idx_scored_events_dedup      ON scored_events (coil_id, stand, reading_id DESC);
CREATE INDEX idx_scored_events_version    ON scored_events (model_version);

-- ---------------------------------------------------------------------------
-- Event-time tumbling-window KPIs (1-minute windows). Upserted by Flink.
-- ---------------------------------------------------------------------------
CREATE TABLE kpi_windows (
  window_start  TIMESTAMP(3),
  window_end    TIMESTAMP(3),
  coils         BIGINT,
  events        BIGINT,
  anomalies     BIGINT,
  anomaly_rate  DOUBLE PRECISION,
  threshold     DOUBLE PRECISION,   -- the score threshold the anomalies count used
  PRIMARY KEY (window_start, window_end)
);

-- ---------------------------------------------------------------------------
-- Retrain history (written by the retrain sidecar: v1 on the first Train, then every retrain).
-- Drives the MODELS "retrain flywheel" panel.
-- ---------------------------------------------------------------------------
CREATE TABLE model_versions (
  version          INT PRIMARY KEY,
  trained_at       TIMESTAMP(3),
  n_train_samples  INT,
  threshold        DOUBLE PRECISION,
  overall_f1       DOUBLE PRECISION,
  overall_pr_auc   DOUBLE PRECISION,
  "precision"      DOUBLE PRECISION,
  recall           DOUBLE PRECISION,
  recall_electric  DOUBLE PRECISION,
  recall_bearing   DOUBLE PRECISION,
  recall_workroll  DOUBLE PRECISION,
  recall_reduction DOUBLE PRECISION,
  trained_on       VARCHAR
);
